### PR TITLE
Feat signing

### PR DESCRIPTION
**Pull request by anegg0**
-Added intro explaining Ethereum message signing basics
-Fixed confusing explanations and erroneous ones
-Added geth prefix / `EthereumSigner` paragraph

### CODE REVIEW

**Comment by KevinSmall** [comment]
I like sections 1 and 2. They are very clear, first "sign" then "verify". I read them and feel I understand them. Some suggested changes:

## 1. Sections 3 and 4
Sections 3 and 4 follow the same pattern "sign" then "verify", which is good, but they leave me with unanswered questions:
* Why would we want/need to hash the message at all?
* Why are we calling different methods from 1 and 2 to hash and sign the message in one go? Couldn't we hash it ourselves before calling the same methods as in 1 and 2?

## 2. Section 5
Section 5 I don't follow. Can we follow the "sign" and "verify" pattern of section 1 and 2? Perhaps add some comments in the code to show which bit is doing what relating to the main body text.

## 3. Knowing which method to use
Say I receive a message and a signature. How can I tell which technique to use to check if the sig is valid? Do I have to try types 1/2 and 3/4 and 5 all and see which works? Or does the sender need to tell me which method to use as well?

## 4. Clarification
Locate "enable the receiver of a signed message to know what they are signing".
Why would the receiver of a signed message want to sign it again? Does it mean more like "know what they are dealing with".

## 5. Typos
There are minor typos which I'll put into a commit which you can review rather than document (just waiting on access).

**Comment by KevinSmall** [comment]
## 6. Etherscan link
This one is a question. The etherscan link https://etherscan.io/verifySig shows a page that asks for these items:
[Step 1] Address
[Step 2] Message Signature Hash
[Step 3] Enter the original message that was signed

Which method of ours does this correspond to? Is this our method 3 and 4 (hashed message).

**Comment by KevinSmall** [comment]
## 5. Typos
Proposed typo fixes are here: https://github.com/Nethereum/Nethereum.Workbooks/pull/68/commits/345633bf90a44b5d2e05007dd96047b4e8ce4641

**Comment by anegg0** [comment]
> I like sections 1 and 2. They are very clear, first "sign" then "verify". I read them and feel I understand them. Some suggested changes:
> 
> ## 1. Sections 3 and 4
> Sections 3 and 4 follow the same pattern "sign" then "verify", which is good, but they leave me with unanswered questions:
> 
> * Why would we want/need to hash the message at all?
here's my current understanding: in the Ethereum context, hashing messages is required to sign them, it's a convention to make sure that the 'message' part of the signature prefix will always be 32 bytes long, making for a consistent serialization.
> * Why are we calling different methods from 1 and 2 to hash and sign the message in one go? Couldn't we hash it ourselves before calling the same methods as in 1 and 2?
> 
I would agree, I'm still not sure what these hashing methods are for, couldn't get clarifications, so i removed them from the article in order to not generate confusion.
> ## 2. Section 5
> Section 5 I don't follow. Can we follow the "sign" and "verify" pattern of section 1 and 2? Perhaps add some comments in the code to show which bit is doing what relating to the main body text.
> ok, I added more comments, please let me know if it helps, I tried my best to aggregate all i could find, but @juanfranblanco review would really help rectify
> ## 3. Knowing which method to use
> Say I receive a message and a signature. How can I tell which technique to use to check if the sig is valid? Do I have to try types 1/2 and 3/4 and 5 all and see which works? Or does the sender need to tell me which method to use as well?
>I  don't know, but upon @juanfranblanco recommendation, I left only EncodeUTF8AndEcRecover in this article. Juan might be able to clarify that point.
> ## 4. Clarification
> Locate "enable the receiver of a signed message to know what they are signing".
> Why would the receiver of a signed message want to sign it again? Does it mean more like "know what they are dealing with".
> you are right, that sentence was wrong, i corrected it.
> ## 5. Typos
> There are minor typos which I'll put into a commit which you can review rather than document (just waiting on access).
Thank you

**Comment by anegg0** [comment]
@KevinSmall, I tried to clarify as much as possible and removed the confusing parts, please let me know if it makes more sense to you.

**Pull request merged**
